Update cd-pipeline.yml

diff --git a/.github/workflows/cd-pipeline.yml b/.github/workflows/cd-pipeline.yml
--- a/.github/workflows/cd-pipeline.yml
+++ b/.github/workflows/cd-pipeline.yml
@@ -33,21 +33,33 @@ jobs:
 
       - name: Azure CLI script
         id: token-gen
-        uses: azure/CLI@v1
-        with:
-          azcliversion: 2.63.0
-          inlineScript: |
-            ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
-            echo "azureAccessToken=$ACCESS_TOKEN" >> $GITHUB_ENV
+        run: |
+          ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
+          if [ -z "$ACCESS_TOKEN" ]; then
+            echo "Failed to retrieve ACCESS_TOKEN"
+            exit 1
+          fi
+          echo "AZURE_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
+
+      - name: Retrieve FQDN
+        run: |
+          export FQDN=$(az containerapp show -n devops-app -g devsecops-lab --query properties.configuration.ingress.fqdn -o tsv)
+          if [ -z "$FQDN" ]; then
+            echo "Failed to retrieve FQDN. Exiting."
+            exit 1
+          else
+            echo "FQDN: $FQDN"
+          fi
+          echo "FQDN=$FQDN" >> $GITHUB_ENV
 
       - name: Upload reports
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          AZURE_ACCESS_TOKEN: ${{ env.azureAccessToken }}
+          AZURE_ACCESS_TOKEN: ${{ env.AZURE_ACCESS_TOKEN }}
+          FQDN: ${{ env.FQDN }}
         run: |
-          export FQDN=$(az containerapp show -n devops-app -g devsecops-lab --query properties.configuration.ingress.fqdn -o tsv)
-          echo "FQDN: $FQDN"
           WEEK1_APP=$(curl -X POST -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" -d "https://$FQDN" https://devsecops-ver.azurewebsites.net/api/week1-app)
           echo "Week1 app upload: $WEEK1_APP"
+          
           WEEK2_SUBMIT=$(curl -X POST -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" -d "https://$FQDN" https://devsecops-ver.azurewebsites.net/api/week2-submit)
           echo "Week2 submit: $WEEK2_SUBMIT"
